# Generated by Django 5.2.4 on 2025-07-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SPORent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('district_code', models.CharField(max_length=20)),
                ('district_name', models.CharField(max_length=100)),
                ('spo_code', models.CharField(max_length=50)),
                ('spo_name', models.CharField(max_length=100)),
                ('stru_grp', models.CharField(max_length=50)),
                ('spo_status', models.CharField(max_length=50)),
                ('inception_date', models.DateField()),
                ('godown_address', models.TextField()),
                ('owner_code', models.CharField(max_length=50)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_address', models.TextField()),
                ('owner_contact', models.CharField(max_length=50)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_gst', models.CharField(max_length=30)),
                ('owner_pan', models.CharField(max_length=30)),
                ('bank_account_name', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('branch_name_bank', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=20)),
                ('depot_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('office_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('open_space_sqft', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_space', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('days_count', models.IntegerField()),
                ('security_deposit_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit_doc', models.CharField(max_length=100)),
                ('rent_pm', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearly_hike_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('latitude', models.CharField(max_length=30)),
                ('longitude', models.CharField(max_length=30)),
                ('vacation_letter', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
            ],
        ),
    ]
