# Generated by Django 5.2.4 on 2025-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='cfa_agreement',
            field=models.FileField(blank=True, help_text='CFA Agreement / Renewal (approx. 1 to 8 MB)', null=True, upload_to='spo_rent/cfa_agreements/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_acceptance_letter',
            field=models.FileField(blank=True, help_text='Closure Acceptance Letter (approx. 1 MB)', null=True, upload_to='spo_rent/closure_acceptance/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_letter',
            field=models.FileField(blank=True, help_text='Closure Letter (approx. 1 MB)', null=True, upload_to='spo_rent/closure_letters/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='ff_letter_calc',
            field=models.FileField(blank=True, help_text='F&F Letter & Calc. (approx. 10 MB)', null=True, upload_to='spo_rent/ff_letters/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit',
            field=models.FileField(blank=True, help_text='Security Deposit (approx. 1 MB)', null=True, upload_to='spo_rent/security_deposits/'),
        ),
    ]
