# Generated by Django 5.2.4 on 2025-07-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_sporent_cfa_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='status',
            field=models.IntegerField(default=1, help_text='Status: 1=Active, 0=Inactive'),
        ),
    ]
