# Generated by Django 5.2.4 on 2025-07-22 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_cfaagreement_spo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SPO',
        ),
    ]
