# Generated by Django 5.2.4 on 2025-07-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_spo_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=200)),
                ('source_plant_code', models.CharField(max_length=50)),
                ('source_plant_name', models.CharField(max_length=200)),
                ('operating_in_multiple_plant', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('list_of_plant', models.TextField(blank=True)),
                ('transporter_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Close', 'Close')], max_length=50)),
                ('inception_date', models.DateField()),
                ('agreement_from_date', models.DateField()),
                ('agreement_to_date', models.DateField()),
                ('transporter_code', models.CharField(max_length=50, unique=True)),
                ('transporter_name', models.CharField(max_length=200)),
                ('transporter_address', models.TextField()),
                ('owner_managing_partner', models.CharField(max_length=200)),
                ('owner_contact_no', models.CharField(max_length=20)),
                ('transporter_mail_id', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=20)),
                ('pan_no', models.CharField(max_length=20)),
                ('bank_account_name', models.CharField(max_length=200)),
                ('bank_account_no', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch_name', models.CharField(max_length=200)),
                ('bank_ifsc_code', models.CharField(max_length=20)),
                ('customer_code_for_invoicing', models.CharField(max_length=50)),
                ('security_deposit_rs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('security_deposit_doc_dd', models.CharField(max_length=200)),
                ('reg_office_destination_code', models.CharField(max_length=50)),
                ('closure_date', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50)),
                ('transporter_agreement', models.FileField(blank=True, null=True, upload_to='transporter_agreements/')),
                ('closure_letter', models.FileField(blank=True, null=True, upload_to='transporter_agreements/')),
                ('closure_acceptance_letter', models.FileField(blank=True, null=True, upload_to='transporter_agreements/')),
                ('ff_letter_calc', models.FileField(blank=True, null=True, upload_to='transporter_agreements/')),
                ('security_deposit', models.FileField(blank=True, null=True, upload_to='transporter_agreements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transporter Agreement',
                'verbose_name_plural': 'Transporter Agreements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='cfaagreement',
            options={'ordering': ['-created_at'], 'verbose_name': 'CFA Agreement', 'verbose_name_plural': 'CFA Agreements'},
        ),
        migrations.AlterModelOptions(
            name='sporent',
            options={'ordering': ['-id'], 'verbose_name': 'SPO Rent', 'verbose_name_plural': 'SPO Rents'},
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='agreement_document',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='branch_name_bank',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='closure_document',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='renewal_document',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='security_deposit_doc',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='security_deposit_document',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='branch_name_bank',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='cfa_agreement',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='closure_acceptance_letter',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='closure_letter',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='days_count',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='depot_sqft',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='district_code',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='ff_letter_calc',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='godown_address',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='office_sqft',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='open_space_sqft',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='owner_code',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='owner_contact',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='owner_gst',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='owner_pan',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='security_deposit',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='security_deposit_doc',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='security_deposit_paid',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='spo_status',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='stru_grp',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='total_space',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='vacation_letter',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='yearly_hike_percent',
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='cfa_agreement',
            field=models.FileField(blank=True, null=True, upload_to='cfa_agreements/'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='closure_acceptance_letter',
            field=models.FileField(blank=True, null=True, upload_to='cfa_agreements/'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='closure_letter',
            field=models.FileField(blank=True, null=True, upload_to='cfa_agreements/'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='ff_letter_calc',
            field=models.FileField(blank=True, null=True, upload_to='cfa_agreements/'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='security_deposit',
            field=models.FileField(blank=True, null=True, upload_to='cfa_agreements/'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='security_deposit_doc_ref_dd',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='agreement_from_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='agreement_renewal',
            field=models.CharField(choices=[('Agreement', 'Agreement'), ('Renewal', 'Renewal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='agreement_to_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='bank_account_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='bank_account_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='bank_ifsc_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='branch_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_mail_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='destination_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='district_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='district_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='godown_address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='gst_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='inception_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='owner_contact_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='pan_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='security_deposit_rs',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='spo_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='spo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='stru_grp',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='spo_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
