# Generated by Django 5.2.4 on 2025-07-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_transporteragreement_alter_cfaagreement_options_and_more'),
    ]

    operations = [
        # Add new fields to SPORent model
        migrations.AddField(
            model_name='sporent',
            name='district_code',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='stru_grp',
            field=models.CharField(max_length=100, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50, default='Active'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='agreement_renewal',
            field=models.CharField(choices=[('Agreement', 'Agreement'), ('Renewal', 'Renewal')], max_length=50, default='Agreement'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='agreement_from_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='agreement_to_date',
            field=models.DateField(default='2025-12-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='godown_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_code',
            field=models.CharField(max_length=50, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='owner_contact_no',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_mail_id',
            field=models.EmailField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='gst_no',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='pan_no',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='bank_account_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='bank_branch_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='destination_code',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit_rs',
            field=models.DecimalField(decimal_places=2, max_digits=12, default=0),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit_doc_ref_dd',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporent',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sporent',
            name='transporter_agreement',
            field=models.FileField(blank=True, help_text='Transporter Agreement (approx. 8 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_letter',
            field=models.FileField(blank=True, help_text='Closure Letter (approx. 1 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_acceptance_letter',
            field=models.FileField(blank=True, help_text='Closure Acceptance Letter (approx. 1 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='ff_letter_calc',
            field=models.FileField(blank=True, help_text='F&F Letter & Calc. (approx. 10 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit',
            field=models.FileField(blank=True, help_text='Security Deposit (approx. 1 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-22T17:04:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Update existing fields
        migrations.AlterField(
            model_name='sporent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50, default='Active'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='branch_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='district_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='spo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='sporent',
            name='owner_email',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='rent_pm',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='to_date',
        ),
    ]
