# Generated by Django 5.2.4 on 2025-07-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20250722_2235'),
    ]

    operations = [
        # Add only the missing cfa_code field that's causing the error
        migrations.AddField(
            model_name='sporent',
            name='cfa_code',
            field=models.CharField(max_length=50, unique=True, null=True, blank=True),
        ),
    ]
