# Generated by Django 5.2.4 on 2025-07-22 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20250722_2242'),
    ]

    operations = [
        # Add missing fields
        migrations.AddField(
            model_name='sporent',
            name='cfa_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='owner_contact_no',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='cfa_mail_id',
            field=models.EmailField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='gst_no',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='pan_no',
            field=models.CharField(max_length=20, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='bank_account_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='bank_branch_name',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='destination_code',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit_rs',
            field=models.DecimalField(max_digits=12, decimal_places=2, default=0),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit_doc_ref_dd',
            field=models.CharField(max_length=200, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sporent',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sporent',
            name='transporter_agreement',
            field=models.FileField(blank=True, help_text='Transporter Agreement (approx. 8 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_letter',
            field=models.FileField(blank=True, help_text='Closure Letter (approx. 1 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='closure_acceptance_letter',
            field=models.FileField(blank=True, help_text='Closure Acceptance Letter (approx. 1 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='ff_letter_calc',
            field=models.FileField(blank=True, help_text='F&F Letter & Calc. (approx. 10 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit',
            field=models.FileField(blank=True, help_text='Security Deposit (approx. 1 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-22T18:14:00Z'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sporent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        
        # Update status field to use choices
        migrations.AlterField(
            model_name='sporent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50, default='Active'),
        ),
        
        # Update field lengths to match model
        migrations.AlterField(
            model_name='sporent',
            name='branch_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='district_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='spo_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='owner_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_name',
            field=models.CharField(max_length=200),
        ),
    ]
