# Generated by Django 5.2.4 on 2025-07-23 05:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20250722_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nfa_no', models.CharField(max_length=50, unique=True, verbose_name='NFA No')),
                ('nfa_date', models.DateField(verbose_name='NFA Date')),
                ('nature_of_approval', models.CharField(choices=[('spo_rent', 'SPO Rent Agreement'), ('cfa_agreement', 'CFA Agreement'), ('transporter_agreement', 'Transporter Agreement'), ('financial', 'Financial Approval'), ('operational', 'Operational Approval'), ('compliance', 'Compliance Approval'), ('other', 'Other')], max_length=50, verbose_name='Nature of Approval')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('subject', models.TextField(verbose_name='Subject')),
                ('valid_from', models.DateField(verbose_name='Valid From')),
                ('valid_to', models.DateField(verbose_name='Valid To')),
                ('remark', models.TextField(blank=True, verbose_name='Remark')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_created', to='auth.user')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approvals_approved', to='auth.user')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approvals',
                'ordering': ['-created_at'],
            },
        ),
    ]
