# Generated by Django 5.2.4 on 2025-07-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20250723_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndianState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('is_union_territory', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Indian State',
                'verbose_name_plural': 'Indian States',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='sporent',
            options={'ordering': ['-created_at'], 'verbose_name': 'SPO Rent', 'verbose_name_plural': 'SPO Rents'},
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='agreement_renewal',
            field=models.CharField(choices=[('Agreement', 'Agreement'), ('Renewal', 'Renewal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='cfa_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='security_deposit_rs',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50),
        ),
    ]
