# Generated by Django 5.2.4 on 2025-07-23 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_fix_cfa_code_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=100, unique=True)),
                ('state_code', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'mas_state',
                'ordering': ['state_name'],
            },
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstate', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstate', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transporteragreement',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstate', verbose_name='State'),
        ),
        migrations.CreateModel(
            name='MasStateBranch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state_branch_name', models.CharField(max_length=100)),
                ('state_branch_code', models.CharField(max_length=20)),
                ('state', models.ForeignKey(db_column='state_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstate')),
            ],
            options={
                'verbose_name': 'State Branch',
                'verbose_name_plural': 'State Branches',
                'db_table': 'mas_state_branch',
                'ordering': ['state__state_name', 'state_branch_name'],
            },
        ),
    ]
