# Generated by Django 5.2.4 on 2025-07-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_add_mas_state_models_and_update_state_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='attachment',
            field=models.FileField(blank=True, help_text='Upload supporting documents (PDF, DOC, DOCX, JPG, PNG - Max 10MB)', null=True, upload_to='approval_attachments/', verbose_name='Attachment'),
        ),
    ]
