# Generated by Django 5.2.4 on 2025-07-24 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_approval_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='nature_of_approval',
            field=models.CharField(choices=[('plant', 'Plant'), ('other', 'Other'), ('spo', 'SPO'), ('internal', 'Internal'), ('dc_wc', 'DC/WC'), ('cmd_approval', 'CMD Approval'), ('shortage', 'Shortage'), ('rp_loss', 'RP Loss'), ('halting', 'Halting')], max_length=50, verbose_name='Nature of Approval'),
        ),
    ]
