# Generated by Django 5.2.4 on 2025-07-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_alter_approval_nature_of_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstatebranch', verbose_name='Branch'),
        ),
    ]
