# Generated by Django 5.2.4 on 2025-07-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_sporent_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporent',
            name='stru_grp',
            field=models.CharField(choices=[('Road', 'Road'), ('Rail', 'Rail'), ('TDP', 'TDP')], max_length=100, verbose_name='Structure Group'),
        ),
    ]
