# Generated by Django 5.2.4 on 2025-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_sporent_stru_grp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporent',
            name='cfa_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], max_length=50, verbose_name='SPO Status'),
        ),
    ]
