# Generated by Django 5.2.4 on 2025-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_sporent_cfa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='owner_address',
            field=models.TextField(blank=True, null=True, verbose_name='Owner Address'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='owner_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Owner Code'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='owner_gst',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Owner GST'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='owner_pan',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Owner PAN'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='cfa_mail_id',
            field=models.EmailField(max_length=254, verbose_name='Owner Mail ID'),
        ),
    ]
