# Generated by Django 5.2.4 on 2025-07-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_sporent_owner_address_sporent_owner_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporent',
            name='destination_code',
            field=models.CharField(max_length=50, verbose_name='Depot Sq.Ft'),
        ),
    ]
