# Generated by Django 5.2.4 on 2025-07-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_sporent_destination_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='office_sqft',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Office Sq.ft'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='open_space_sqft',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Open Space Sq.ft'),
        ),
    ]
