# Generated by Django 5.2.4 on 2025-07-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_sporent_office_sqft_sporent_open_space_sqft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporent',
            name='transporter_agreement',
            field=models.FileField(blank=True, help_text='Rent Agreement', null=True, upload_to='spo_rent_attachments/', verbose_name='Rent Agreement'),
        ),
    ]
