# Generated by Django 5.2.4 on 2025-07-24 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_sporent_transporter_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporent',
            name='agreement_from_date',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='agreement_renewal',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='agreement_to_date',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='cfa_address',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='cfa_code',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='cfa_name',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='closure_date',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='gst_no',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='pan_no',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='security_deposit_doc_ref_dd',
        ),
        migrations.RemoveField(
            model_name='sporent',
            name='security_deposit_rs',
        ),
    ]
