# Generated by Django 5.2.4 on 2025-07-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_remove_sporent_agreement_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='rental_from_date',
            field=models.DateField(blank=True, null=True, verbose_name='From Date'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='rental_to_date',
            field=models.DateField(blank=True, null=True, verbose_name='To Date'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit_doc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Security Deposit Doc. / Ref. / DD'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='security_deposit_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Security Deposit Paid'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='total_space',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Total Space'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='vacation_letter',
            field=models.FileField(blank=True, null=True, upload_to='spo_rent_attachments/', verbose_name='Vacation Letter'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='yearly_hike_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Yearly Hike %'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_account_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_branch_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='cfa_mail_id',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Owner Mail ID'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='godown_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='owner_contact_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='owner_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
