# Generated by Django 5.2.4 on 2025-07-27 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_add_missing_fields_to_sporent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='capacity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacity'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='days_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Count'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='owner_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Owner Email'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='rent_pm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Rent PM'),
        ),
    ]
