# Generated by Django 5.2.4 on 2025-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_add_missing_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfaagreement',
            name='stru_grp',
            field=models.CharField(choices=[('Road', 'Road'), ('Rail', 'Rail'), ('TDP', 'TDP'), ('Others', 'Others')], max_length=100),
        ),
    ]
