# Generated by Django 5.2.4 on 2025-07-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_cfaagreement_stru_grp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sporent',
            name='stru_grp',
            field=models.CharField(choices=[('Road', 'Road'), ('Rail', 'Rail'), ('TDP', 'TDP'), ('Others', 'Others')], max_length=100, verbose_name='Structure Group'),
        ),
    ]
