# Generated by Django 5.2.4 on 2025-07-27 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_sporent_stru_grp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteragreement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstatebranch', verbose_name='Branch'),
        ),
    ]
