# Generated by Django 5.2.4 on 2025-07-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_transporteragreement_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporteragreement',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
