# Generated by Django 5.2.4 on 2025-07-27 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_transporteragreement_district_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sporent',
            name='owner_email',
        ),
    ]
