# Generated by Django 5.2.4 on 2025-08-05 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_owner_email_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasConstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Construction Type',
                'verbose_name_plural': 'Construction Types',
                'db_table': 'mas_construction',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Reminder Name')),
                ('reminder_type', models.CharField(choices=[('spo_rent_renewal', 'SPO Rent Renewal'), ('spo_rent_expiry', 'SPO Rent Expiry'), ('spo_rent_payment', 'SPO Rent Payment'), ('cfa_agreement_renewal', 'CFA Agreement Renewal'), ('cfa_agreement_expiry', 'CFA Agreement Expiry'), ('transporter_agreement_renewal', 'Transporter Agreement Renewal'), ('transporter_agreement_expiry', 'Transporter Agreement Expiry'), ('payment_due', 'Payment Due'), ('document_expiry', 'Document Expiry'), ('general', 'General Update')], max_length=50, verbose_name='Reminder Type')),
                ('subject_template', models.CharField(max_length=300, verbose_name='Email Subject Template')),
                ('message_template', models.TextField(verbose_name='Email Message Template')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20, verbose_name='Status')),
                ('is_automated', models.BooleanField(default=False, verbose_name='Automated Reminder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Reminder',
                'verbose_name_plural': 'Email Reminders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('custom', 'Custom')], max_length=20, verbose_name='Frequency')),
                ('day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True, verbose_name='Day of Week')),
                ('day_of_month', models.IntegerField(blank=True, null=True, verbose_name='Day of Month')),
                ('time_of_day', models.TimeField(default='09:00', verbose_name='Time of Day')),
                ('custom_days_before_expiry', models.IntegerField(blank=True, null=True, verbose_name='Days Before Expiry')),
                ('custom_days_after_expiry', models.IntegerField(blank=True, null=True, verbose_name='Days After Expiry')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Last Run')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='Next Run')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_created', to=settings.AUTH_USER_MODEL)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='dashboard.emailreminder', verbose_name='Email Reminder')),
            ],
            options={
                'verbose_name': 'Reminder Schedule',
                'verbose_name_plural': 'Reminder Schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Recipient Email')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Recipient Name')),
                ('record_type', models.CharField(max_length=50, verbose_name='Record Type')),
                ('record_id', models.CharField(max_length=50, verbose_name='Record ID')),
                ('subject', models.CharField(max_length=300, verbose_name='Email Subject')),
                ('message', models.TextField(verbose_name='Email Message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('retry_count', models.IntegerField(default=0, verbose_name='Retry Count')),
                ('scheduled_at', models.DateTimeField(verbose_name='Scheduled At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.emailreminder', verbose_name='Reminder')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.reminderschedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Reminder Log',
                'verbose_name_plural': 'Reminder Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('template_type', models.CharField(choices=[('spo_rent', 'SPO Rent'), ('cfa_agreement', 'CFA Agreement'), ('transporter_agreement', 'Transporter Agreement'), ('payment', 'Payment'), ('general', 'General')], max_length=50, verbose_name='Template Type')),
                ('subject', models.CharField(max_length=300, verbose_name='Email Subject')),
                ('body', models.TextField(verbose_name='Email Body')),
                ('available_variables', models.TextField(blank=True, help_text='List of available variables for this template', verbose_name='Available Variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Template',
                'verbose_name_plural': 'Reminder Templates',
                'ordering': ['-created_at'],
            },
        ),
    ]
