# Generated by Django 5.2.4 on 2025-08-05 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_masconstruction_emailreminder_reminderschedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sporent',
            name='nature_of_construction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.masconstruction', verbose_name='Nature of Construction'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Partnership', 'Partnership'), ('Company', 'Company'), ('LLP', 'LLP'), ('Trust', 'Trust'), ('Society', 'Society'), ('Others', 'Others')], max_length=50, null=True, verbose_name='Partner Type'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='pin_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Pin Code'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='renewal_with',
            field=models.CharField(blank=True, choices=[('Agreement', 'Agreement'), ('Renewal', 'Renewal')], max_length=50, null=True, verbose_name='Renewal With'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='sale_organization',
            field=models.CharField(blank=True, choices=[('Chettinad', 'Chettinad'), ('Anjani', 'Anjani')], max_length=50, null=True, verbose_name='Sale Organization'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='stamp_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stamp Name'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='stamp_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Stamp No'),
        ),
    ]
