# Generated by Django 5.2.4 on 2025-08-06 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_sporent_nature_of_construction_sporent_partner_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasPartner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Partner Type',
                'verbose_name_plural': 'Partner Types',
                'db_table': 'mas_partner',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='sporent',
            name='closure_acceptance_letter',
            field=models.FileField(blank=True, help_text='Closure Acceptance Letter (Max file size: 10 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='closure_letter',
            field=models.FileField(blank=True, help_text='Closure Letter (Max file size: 10 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='ff_letter_calc',
            field=models.FileField(blank=True, help_text='F&F Letter & Calc. (Max file size: 10 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='security_deposit',
            field=models.FileField(blank=True, help_text='Security Deposit (Max file size: 10 MB)', null=True, upload_to='spo_rent_attachments/'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='transporter_agreement',
            field=models.FileField(blank=True, help_text='Rent Agreement (Max file size: 10 MB)', null=True, upload_to='spo_rent_attachments/', verbose_name='Rent Agreement'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='vacation_letter',
            field=models.FileField(blank=True, help_text='Vacation Letter (Max file size: 10 MB)', null=True, upload_to='spo_rent_attachments/', verbose_name='Vacation Letter'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='partner_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.maspartner', verbose_name='Partner Type'),
        ),
        migrations.CreateModel(
            name='MasPartnerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Partner Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.TextField(verbose_name='Address')),
                ('mail_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('aadhar_no', models.CharField(max_length=12, verbose_name='Aadhar Number')),
                ('pan_no', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('partner_join_date', models.DateField(verbose_name='Partner Join Date')),
                ('partner_end_date', models.DateField(blank=True, null=True, verbose_name='Partner End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partners_created', to=settings.AUTH_USER_MODEL)),
                ('spo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='dashboard.sporent', verbose_name='SPO')),
            ],
            options={
                'verbose_name': 'Partner Detail',
                'verbose_name_plural': 'Partner Details',
                'db_table': 'mas_partner_details',
                'ordering': ['-created_at'],
                'unique_together': {('spo', 'aadhar_no')},
            },
        ),
    ]
