# Generated by Django 5.2.4 on 2025-08-08 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_maspartner_alter_sporent_closure_acceptance_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFAPartnerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Partner Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.TextField(verbose_name='Address')),
                ('mail_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('aadhar_no', models.CharField(max_length=12, verbose_name='Aadhar Number')),
                ('pan_no', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('partner_join_date', models.DateField(verbose_name='Partner Join Date')),
                ('partner_end_date', models.DateField(blank=True, null=True, verbose_name='Partner End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cfa_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='dashboard.cfaagreement', verbose_name='CFA Agreement')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cfa_partners_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CFA Partner Detail',
                'verbose_name_plural': 'CFA Partner Details',
                'db_table': 'cfa_partner_details',
                'ordering': ['-created_at'],
                'unique_together': {('cfa_agreement', 'aadhar_no')},
            },
        ),
    ]
