# Generated by Django 5.2.4 on 2025-08-08 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_cfapartnerdetails'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='maspartnerdetails',
            table='spo_partner_details',
        ),
    ]
