# Generated by Django 5.2.4 on 2025-08-08 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_rename_mas_partner_details_to_spo_partner_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterPartnerDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Partner Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, verbose_name='Gender')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('address', models.TextField(verbose_name='Address')),
                ('mail_id', models.EmailField(max_length=254, verbose_name='Email ID')),
                ('aadhar_no', models.CharField(max_length=12, verbose_name='Aadhar Number')),
                ('pan_no', models.CharField(max_length=10, verbose_name='PAN Number')),
                ('partner_join_date', models.DateField(verbose_name='Partner Join Date')),
                ('partner_end_date', models.DateField(blank=True, null=True, verbose_name='Partner End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transporter_partners_created', to=settings.AUTH_USER_MODEL)),
                ('transporter_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='dashboard.transporteragreement', verbose_name='Transporter Agreement')),
            ],
            options={
                'verbose_name': 'Transporter Partner Detail',
                'verbose_name_plural': 'Transporter Partner Details',
                'db_table': 'transporter_partner_details',
                'ordering': ['-created_at'],
                'unique_together': {('transporter_agreement', 'aadhar_no')},
            },
        ),
    ]
