# Generated by Django 5.2.4 on 2025-08-11 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_chatbotquestion_chatbotsession_chatbotmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('spo_rent', 'SPO Rent'), ('cfa_agreement', 'CFA Agreement'), ('transporter_agreement', 'Transporter Agreement'), ('spo_partner', 'SPO Partner'), ('cfa_partner', 'CFA Partner'), ('transporter_partner', 'Transporter Partner')], max_length=50, verbose_name='Record Type')),
                ('record_id', models.IntegerField(verbose_name='Record ID')),
                ('record_code', models.CharField(max_length=100, verbose_name='Record Code/Name')),
                ('status', models.CharField(choices=[('waiting_confirmation', 'Waiting for Superior Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='waiting_confirmation', max_length=50, verbose_name='Status')),
                ('approver_remarks', models.TextField(blank=True, verbose_name='Approver Remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Record Creation Date')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_approved', to=settings.AUTH_USER_MODEL, verbose_name='Approved By')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows_submitted', to=settings.AUTH_USER_MODEL, verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalWorkflowHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('updated', 'Updated'), ('comment_added', 'Comment Added')], max_length=50, verbose_name='Action')),
                ('remarks', models.TextField(blank=True, verbose_name='Remarks')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dashboard.approvalworkflow', verbose_name='Workflow')),
            ],
            options={
                'verbose_name': 'Approval Workflow History',
                'verbose_name_plural': 'Approval Workflow Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['record_type', 'record_id'], name='dashboard_a_record__367585_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['status'], name='dashboard_a_status_aaf9f2_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['submitted_by'], name='dashboard_a_submitt_331f79_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['approved_by'], name='dashboard_a_approve_69ebe2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('record_type', 'record_id')},
        ),
    ]
