# Generated by Django 5.2.4 on 2025-08-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_role_masdistrict_menuitem_userrole_usermenuaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='masdistrict',
            options={'ordering': ['name'], 'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
    ]
