# Generated by Django 5.2.4 on 2025-08-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_add_consolidate_attachment_to_cfa_agreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='cfaagreement',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='masdistrict',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='masdistrict',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='transporteragreement',
            name='district_name',
        ),
        migrations.RemoveField(
            model_name='transporteragreement',
            name='type_of_approval',
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.masstatebranch', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.masdistrict', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='cfaagreement',
            name='sale_organization',
            field=models.CharField(blank=True, choices=[('Chettinad', 'Chettinad'), ('Anjani', 'Anjani')], max_length=50, null=True, verbose_name='Sale Organization'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='capacity_mt',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Capacity (In Mt)'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='declaration_rcm',
            field=models.CharField(blank=True, choices=[('Declaration', 'Declaration'), ('RCM', 'RCM')], max_length=20, null=True, verbose_name='Declaration / RCM'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='declaration_status',
            field=models.CharField(blank=True, choices=[('Collected', 'Collected'), ('Pending', 'Pending')], max_length=10, null=True, verbose_name='Declaration Status'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.masdistrict', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='gst_status',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=10, null=True, verbose_name='GST Status'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN Number'),
        ),
        migrations.AddField(
            model_name='sporent',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='State Code'),
        ),
        migrations.AddField(
            model_name='transporteragreement',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.masdistrict', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='cfa_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Notice', 'Under Notice'), ('Closed', 'Closed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cfaagreement',
            name='kyc_document',
            field=models.FileField(blank=True, help_text='KYC Document (Max file size: 50 MB)', null=True, upload_to='cfa_agreements/', verbose_name='KYC Document'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='cfa_status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Notice', 'Under Notice'), ('Closed', 'Closed')], max_length=50, null=True, verbose_name='SPO Status'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='destination_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Depot Sq.Ft'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='district_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='inception_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='spo_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Notice', 'Under Notice'), ('Closed', 'Closed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='stru_grp',
            field=models.CharField(blank=True, choices=[('Road', 'Road'), ('Rail', 'Rail'), ('TDP', 'TDP'), ('Others', 'Others')], max_length=100, null=True, verbose_name='Structure Group'),
        ),
        migrations.AlterField(
            model_name='transporteragreement',
            name='gst_status',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, verbose_name='GST Status'),
        ),
        migrations.AlterField(
            model_name='transporteragreement',
            name='list_of_plant',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='List of Plant'),
        ),
        migrations.AlterField(
            model_name='transporteragreement',
            name='pincode',
            field=models.CharField(max_length=10, verbose_name='PIN Code'),
        ),
        migrations.AlterField(
            model_name='transporteragreement',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Notice', 'Under Notice'), ('Closed', 'Closed')], max_length=50),
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
