# Generated by Django 5.2.4 on 2025-08-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_add_list_of_plant_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteragreement',
            name='list_of_plant',
            field=models.JSONField(blank=True, default=list, help_text='Select multiple plants', null=True, verbose_name='List of Plant'),
        ),
    ]
