# Generated by Django 5.2.4 on 2025-08-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0075_update_list_of_plant_to_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteragreement',
            name='list_of_plant',
            field=models.CharField(blank=True, help_text='Select multiple plants separated by commas', max_length=500, null=True, verbose_name='List of Plant'),
        ),
    ]
