# Generated by Django 5.2.4 on 2025-08-21 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0076_revert_list_of_plant_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteragreement',
            name='customer_code_for_invoicing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
