# Generated by Django 5.2.4 on 2025-08-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0077_make_customer_code_for_invoicing_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transporteragreement',
            name='entity_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Entity Code'),
        ),
    ]
