# Generated by Django 5.2.4 on 2025-08-21 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0078_increase_entity_code_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfaagreement',
            name='entity_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last 5 Characters'),
        ),
        migrations.AlterField(
            model_name='sporent',
            name='entity_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Last 5 Characters'),
        ),
    ]
